### ISSUE TITLE
uThreadCache needs to check stack size

### ISSUE THREAD

**Issue by samanbarghi** [samanbarghi/uThreads#12]
uThreadCache currently just returns a uThread from the list. However, it needs to make sure the stack size of the chosen uThread is larger than the requested stack size.

**Comment by samanbarghi** [comment]
Should there even be various sized uThreads? it can add complexity and overhead to the runtime system. Also for segmented stacks there can be performance overhead according to this Rust documentation: https://mail.mozilla.org/pipermail/rust-dev/2013-November/006314.html

**Comment by martinkarsten** [comment]
I would stick with a default size for now and otherwise simply skip the
cache.

If you want to be slightly more flexible, we could support several
initial stack sizes, but only powers of 2. Then keep an array of thread
pools, indexed by log2(stacksize) - log2(minstack).

What's the overhead of segmented stacks and can we even support it in a
pure library? Probably not...

**Comment by samanbarghi** [comment]
The best approach for now in terms of simplicity and performance is using fixed size stacks. So I close the issue.
